from __future__ import annotations

import ast
import importlib

from mainline_boundary_helpers import (
    INVALID_RELATIVE_IMPORT,
    PACKAGE_DIR,
    iter_imported_modules,
    matches_module_prefix,
)

LAYER_ALLOWED_PREFIXES = {
    "platform": ("research_pipeline.platform",),
    "domain": ("research_pipeline.platform", "research_pipeline.domain"),
    "research": (
        "research_pipeline.platform",
        "research_pipeline.domain",
        "research_pipeline.research",
    ),
    "simulation": (
        "research_pipeline.platform",
        "research_pipeline.domain",
        "research_pipeline.simulation",
    ),
    "catalog": (
        "research_pipeline.platform",
        "research_pipeline.domain",
        "research_pipeline.catalog",
    ),
    "data_plane": (
        "research_pipeline.platform",
        "research_pipeline.domain",
        "research_pipeline.catalog",
        "research_pipeline.data_plane",
    ),
    "results": (
        "research_pipeline.platform",
        "research_pipeline.data_plane",
        "research_pipeline.runtime",
        "research_pipeline.results",
    ),
    "evidence": (
        "research_pipeline.platform",
        "research_pipeline.domain",
        "research_pipeline.results",
        "research_pipeline.extensions.verifier_bundle",
        "research_pipeline.evidence",
    ),
    "packages": (
        "research_pipeline.platform",
        "research_pipeline.data_plane",
        "research_pipeline.evidence",
        "research_pipeline.research",
        "research_pipeline.results.compiler",
        "research_pipeline.results.contracts",
        "research_pipeline.packages",
    ),
    "extensions": (
        "research_pipeline.platform",
        "research_pipeline.extensions",
    ),
    "runtime": (
        "research_pipeline.platform",
        "research_pipeline.domain",
        "research_pipeline.research",
        "research_pipeline.simulation",
        "research_pipeline.catalog",
        "research_pipeline.data_plane",
        "research_pipeline.evidence",
        "research_pipeline.extensions",
        "research_pipeline.results.contracts",
        "research_pipeline.runtime",
    ),
    "application": (
        "research_pipeline.platform",
        "research_pipeline.domain",
        "research_pipeline.research",
        "research_pipeline.simulation",
        "research_pipeline.catalog",
        "research_pipeline.data_plane",
        "research_pipeline.evidence",
        "research_pipeline.results",
        "research_pipeline.runtime",
        "research_pipeline.application",
    ),
    "operations": (
        "research_pipeline.platform",
        "research_pipeline.extensions",
        "research_pipeline.evidence",
        "research_pipeline.runtime",
        "research_pipeline.operations",
    ),
}
EXPECTED_PUBLIC_API = {
    "platform": {
        "BUILD_MANIFEST_VERSION",
        "CANONICAL_JSON_V1_VERSION",
        "DEPENDENCY_LOCK_VERSION",
        "GATE_RECEIPT_VERSION",
        "LOCAL_SUPPLY_CHAIN_STATUS",
        "RELEASE_ACCEPTANCE_INPUT_VERSION",
        "RELEASE_ENVELOPE_VERSION",
        "REQUIRED_GATE_IDS",
        "TYPED_CANONICAL_V1_VERSION",
        "BuildManifest",
        "CanonicalEncodingError",
        "CausalTimeContractError",
        "CORE_FEATURE_TIME_COLUMNS",
        "CORE_LABEL_TIME_COLUMNS",
        "CURRENT_MINUTE_CAPABILITY_MANIFEST_HASH",
        "CURRENT_MINUTE_CAPABILITY_MANIFEST_REVISION",
        "EXECUTION_CAPABILITY_MATRIX",
        "MainlineError",
        "TradingCapabilityError",
        "MINUTE_INTERVALS",
        "MINUTE_CAPABILITY_BINDING_VERSION",
        "MINUTE_CAPABILITY_MANIFEST_VERSION",
        "MINUTE_CAPABILITY_REQUIRED_CONSUMERS",
        "MinuteInventoryObservation",
        "MinuteAssetCoverage",
        "MinuteCapabilityInstrument",
        "MinuteCapabilityManifest",
        "MinuteCapabilityManifestError",
        "ReleaseAcceptanceInput",
        "ReleaseEnvelope",
        "ReleaseEnvelopeError",
        "ReleaseGateReceipt",
        "canonical_json",
        "attach_core_feature_time_facts",
        "attach_core_label_time_facts",
        "build_core_feature_time_facts",
        "error_code_for_exception",
        "fingerprint",
        "installed_distribution_digest",
        "load_build_manifest",
        "load_minute_capability_manifest",
        "require_declared_trading_capability",
        "typed_canonical_bytes",
        "typed_canonical_hash",
        "validate_feature_time_facts",
        "validate_label_time_facts",
        "verify_dependency_distribution_lock",
        "verify_release_envelope",
    },
    "domain": {
        "CN_MARKET_TIMEZONE",
        "DomainContractError",
        "FinancialTimeTrace",
        "FUTURES_SESSION_CLOSE_BUNDLE_RESOURCE",
        "FUTURES_SESSION_CLOSE_BUNDLE_VERSION",
        "FuturesSessionCloseError",
        "FuturesSessionClosePolicyBundle",
        "FixedValue",
        "CorporateAction",
        "Instrument",
        "InstrumentAlias",
        "InstrumentId",
        "InstrumentKey",
        "MarketEvent",
        "MarketRuleSnapshot",
        "CURRENT_MINUTE_RULE_BUNDLE_HASH",
        "CURRENT_MINUTE_RULE_COVERAGE_HASH",
        "MINUTE_RULE_BUNDLE_VERSION",
        "MinuteRuleBinding",
        "MinuteRuleResolver",
        "MinuteRuleSnapshot",
        "MinuteRuleSnapshotBundle",
        "MinuteRuleSnapshotError",
        "MinuteRuleSource",
        "Money",
        "OrderIntent",
        "OrderIntentV1",
        "LegacyOrderIntent",
        "Price",
        "RuleBinding",
        "SESSION_POLICY_BUNDLE_VERSION",
        "SESSION_POLICY_VERSION",
        "SESSION_COMPLETED_BAR_BOUNDARY",
        "SESSION_EFFECTIVE_INTERVAL_BOUNDARY",
        "SESSION_INSTANT_BOUNDARY",
        "SessionAssignmentError",
        "SessionAssignmentPolicy",
        "SessionCalendarError",
        "SessionCalendarResolver",
        "SessionInstrumentMetadata",
        "SessionPolicyBundle",
        "SessionPolicyRevision",
        "SessionSegment",
        "SessionSegmentTemplate",
        "Signal",
        "TargetPortfolio",
        "TargetWeight",
        "PortfolioTarget",
        "PortfolioTargetEntry",
        "TradingRuleBinding",
        "INSTRUMENT_KEY_VERSION",
        "ORDER_INTENT_VERSION",
        "PORTFOLIO_TARGET_VERSION",
        "TRADING_RULE_BINDING_VERSION",
        "EXECUTION_CAPABILITY_MATRIX",
        "TimeContractError",
        "TradingSessionCalendar",
        "TradingSession",
        "build_cn_daily_next_open_trace",
        "build_completed_bar_trace",
        "assign_completed_bars",
        "reconcile_session_aggregates",
        "load_session_policy_bundle",
        "load_futures_session_close_bundle",
        "load_minute_rule_snapshot_bundle",
        "parse_session",
        "require_integer_quantity",
        "require_strict_session_order",
        "resolve_corporate_actions",
        "instrument_key_from_legacy",
        "portfolio_target_from_legacy",
        "require_declared_trading_capability",
        "resolve_instrument_alias",
        "resolve_market_rule",
        "validate_label_session_horizon",
    },
    "research": {
        "ESTIMAND_SPEC_VERSION",
        "FEATURE_SET_ARTIFACT_VERSION",
        "HYPOTHESIS_SPEC_VERSION",
        "LABEL_ARTIFACT_VERSION",
        "RESEARCH_SEMANTICS_VERSION",
        "RESEARCH_TIME_WINDOW_VERSION",
        "EstimandSpec",
        "FeatureSetArtifact",
        "HypothesisSpec",
        "LabelArtifact",
        "ResearchSemantics",
        "ResearchSemanticsError",
        "ResearchTimeWindow",
        "assign_quantile_buckets",
        "portfolio_metric_values",
        "select_top_n_codes",
        "stable_score_order",
    },
    "simulation": {
        "BAR_TCA_ARTIFACT_VERSION",
        "BAR_TCA_ORACLE_INPUT_VERSION",
        "BAR_TCA_POLICY_VERSION",
        "BAR_TCA_RESULT_VERSION",
        "BarTcaFill",
        "BarTcaFormalFill",
        "BarTcaOrder",
        "BarTcaOrderResult",
        "BarTcaPolicy",
        "BarTcaResult",
        "ACCOUNT_CONFIG_VERSION",
        "CAPABILITY_MATRIX_VERSION",
        "SIMULATION_REQUEST_VERSION",
        "AccountConfig",
        "CASH_DAILY_BACKEND",
        "CN_FUTURES_DAILY_BACKEND",
        "EXECUTION_BACKENDS",
        "SIMULATION_INPUT_AVAILABILITY_VERSION",
        "SIMULATION_SEMANTICS_VERSION",
        "SIMULATION_TIMEZONE",
        "SIMULATION_RESULT_CONTRACT_VERSION",
        "SIMULATION_RESULT_SEMANTICS_VERSION",
        "CANONICAL_SIMULATION_TABLES",
        "CapacityMode",
        "DAILY_EVENT_SIMULATION_VERSION",
        "FUTURES_DAILY_SIMULATION_VERSION",
        "CashExecutionResult",
        "CashReceivable",
        "CashMarketPolicy",
        "DailyCashSimulationResult",
        "ContinuousMapping",
        "ETF_CATEGORIES",
        "EventReplay",
        "ExecutionGroup",
        "ExecutionBackendCapability",
        "FinancialEvent",
        "FuturesFeePolicy",
        "FuturesExecutionRule",
        "FuturesLedgerState",
        "FuturesLeg",
        "FuturesRuleBook",
        "FuturesSimulationResult",
        "FuturesPosition",
        "MarginPolicy",
        "MarginOverride",
        "INTRADAY_EXECUTION_POLICY_VERSION",
        "IntradayExecutionPolicy",
        "IntentToOrderPort",
        "MinuteExecutionBar",
        "OpeningSnapshot",
        "Order",
        "PositionLot",
        "PositionEntitlement",
        "RightsExerciseInstruction",
        "SequenceGap",
        "SimulationContractError",
        "SimulationInputAvailability",
        "SimulationRequest",
        "SimulationResultContract",
        "SimulationResultSemantics",
        "SimulationSemanticsV1",
        "SpotLedgerState",
        "StockPostCloseAudit",
        "TradabilityDecision",
        "TradeReference",
        "evaluate_tradability",
        "audit_stock_after_close",
        "build_cn_daily_simulation_semantics",
        "build_simulation_result_contract",
        "canonical_simulation_table",
        "bar_tca_policy_from_parameters",
        "capacity_claim_ceiling",
        "compile_corporate_action",
        "compile_cn_etf_corporate_action_rows",
        "compile_cn_stock_corporate_action_rows",
        "corporate_action_snapshot_hash",
        "decompose_roll",
        "deterministic_liquidation_order",
        "etf_policy_from_rule",
        "execute_cash_order",
        "group_etf_policies",
        "margin_call_required",
        "normalize_market_events",
        "reduce_futures",
        "reduce_spot",
        "require_visible_nav",
        "require_declared_execution_capability",
        "require_supported_target",
        "resolve_actual_contract",
        "run_bar_tca",
        "run_market_event_loop",
        "run_daily_cash_event_simulation",
        "run_futures_daily_simulation",
        "run_futures_portfolio_simulation",
        "project_cash_daily_result",
        "project_futures_daily_result",
        "build_futures_order_intents",
        "build_futures_portfolio_roll_intents",
        "run_minute_event_simulation",
        "settle_futures_day",
        "stock_policy_from_rule",
        "stock_policy_from_contract",
        "transition_order",
        "verify_simulation_result_artifact",
        "verify_simulation_result_contract",
        "verify_bar_tca_artifact",
        "write_bar_tca_artifact",
        "write_simulation_result_contract",
    },
    "catalog": {
        "ADJUSTMENT_FACTOR_SNAPSHOT_VERSION",
        "ApprovalDecision",
        "CATALOG_CONTRACT_VERSION",
        "CatalogContract",
        "CatalogPreflight",
        "CompiledCatalog",
        "COMPILER_VERSION",
        "CatalogCoverageBaseline",
        "CatalogDriftError",
        "CatalogError",
        "CatalogFinancialSemanticsError",
        "CatalogParseError",
        "CatalogReferenceError",
        "CatalogSourceManifest",
        "DatasetContract",
        "DeclarativeCatalog",
        "DriftAttestation",
        "DriftFinding",
        "DuckDBSourceInspector",
        "FieldContract",
        "FieldFamilySource",
        "LOCK_FORMAT_VERSION",
        "MINUTE_DATASET_SEMANTICS_VERSION",
        "MINUTE_SOURCE_SEMANTICS_VERSION",
        "MinuteDatasetSemantics",
        "MinuteSourceSemantics",
        "AdjustmentDecisionAnchor",
        "AdjustmentFactorSegment",
        "AdjustmentFactorSnapshot",
        "PhysicalBindingContract",
        "PhysicalColumn",
        "PhysicalInventory",
        "ParquetSourceInspector",
        "PolicyContract",
        "TransformContract",
        "TransformDescriptor",
        "build_transform_manifest",
        "catalog_schema_bundle",
        "catalog_source_schema",
        "code_hash_for_transform",
        "compile_catalog",
        "describe_transform",
        "expand_field_family",
        "evaluate_current_drift",
        "load_contract_file",
        "load_contract_payload",
        "load_declarative_catalog",
        "load_default_declarative_catalog",
        "require_approval",
        "require_financial_observation_visible",
        "render_catalog_docs",
        "validate_contract_set",
        "validate_transform_manifest",
        "verify_transform_implementation",
    },
    "runtime": {
        "AUDIT_ENVIRONMENT_VERSION",
        "CACHE_COMPATIBILITY_VERSION",
        "EXECUTION_IDENTITY_VERSION",
        "EXTERNAL_ARTIFACT_COMMIT_VERSION",
        "MINUTE_EXECUTION_PROFILE_VERSION",
        "MINUTE_PARTITION_ALGORITHM_VERSION",
        "MINUTE_PARTITION_CHECKPOINT_VERSION",
        "MINUTE_PARTITION_MANIFEST_VERSION",
        "MINUTE_PARTITION_METRICS_VERSION",
        "MINUTE_RUNTIME_RESULT_VERSION",
        "OPERATOR_DAG_RUN_VERSION",
        "RUNTIME_COMPLETION_METADATA_VERSION",

        "ArtifactRef",
        "AuditEnvironmentManifest",
        "CacheCompatibilityMode",
        "CacheCompatibilityProfile",
        "CheckpointExpectation",
        "CheckpointManifest",
        "CheckpointPolicy",
        "CheckpointStore",
        "DagSpec",
        "DeterminismContext",
        "Edge",
        "EventStore",
        "ExecutionIdentity",
        "ExternalArtifactCommit",
        "ExternalArtifactStore",
        "ExecutionMode",
        "ImplementationDescriptor",
        "ImplementationRegistry",
        "MemoryGovernor",
        "MinuteExecutionIdentity",
        "MinutePartitionExecutionResult",
        "MinutePartitionKey",
        "MinutePartitionManifest",
        "MinutePartitionMetrics",
        "MinutePartitionRuntime",
        "MinutePartitionSpec",
        "MinutePartitionWorkResult",
        "MinuteRuntimeBudget",
        "MinuteRuntimeBudgetError",
        "NodeSpec",
        "PartitionSpec",
        "PROJECT_RUNTIME_IDENTITY_VERSION",
        "ProjectFairQueue",
        "ProjectReadyCandidate",

        "ProjectRuntimeIdentity",
        "ProjectRuntimeInput",

        "ReadyCandidate",
        "ReservationLedger",
        "ResourceBudget",
        "ResourceCapacity",
        "RESOURCE_CALIBRATION_VERSION",
        "RESOURCE_GOVERNOR_VERSION",
        "RESOURCE_OBSERVATION_VERSION",
        "ResourceGovernor",
        "ResourceGovernorConfig",
        "ResourceLease",
        "ResourceObservation",
        "ResourceToken",
        "ResourceUsageSampler",
        "ResourceVector",
        "RecoveryPlan",
        "RetryPolicy",
        "RuntimeAdmissionError",
        "RuntimeContractError",
        "RuntimeCompletionMetadata",
        "RuntimeErrorBase",
        "RuntimeExecutionService",
        "RuntimeEvent",
        "RuntimeGraphError",
        "RuntimeIntegrityError",
        "RuntimeProjection",
        "RuntimeRegistryError",
        "RuntimeNodeContext",
        "RuntimeNodeOutputs",
        "RuntimeNodeValue",
        "RuntimeStateError",
        "RuntimeWorkerError",

        "apply_event",
        "build_production_registry",
        "compile_production_dag",
        "compile_minute_partition_manifest",
        "derive_node_execution_id",
        "derive_partition_seed",
        "derive_run_id",
        "environment_fingerprint",
        "plan_rerun_from",
        "plan_resume",
        "plan_retry_node",
        "project_runtime_identity",
        "stable_partition_keys",
        "stable_partition_merge",
        "stable_minute_instrument_bucket",
    },
    "evidence": {
        "CLAIM_LEVELS",
        "FACET_CONTRACT_VERSION",
        "GATE_STATUSES",
        "VALIDITY_CONTRACT_VERSION",
        "VALIDITY_FACTS_ARTIFACT_TYPE",
        "VALIDITY_FACTS_VERSION",
        "VALIDITY_GATE_IDS",
        "VALIDITY_GATE_REASON_CODES",
        "VALIDITY_REASON_MESSAGES",
        "VERIFICATION_RESULT_VERSION",
        "ArtifactIntegrityFacet",
        "ClaimAssessment",
        "ClaimFacet",
        "ClaimPolicy",
        "EvidenceContractError",
        "FinancialOracleBudget",
        "GateRecomputeRecord",
        "ResearchValidityFacet",
        "ReproducibilityFacet",
        "ValidityFinding",
        "ValidityGateResult",
        "VerificationComparison",
        "VerificationIssue",
        "VerificationReportModel",
        "VerificationResult",
          "VerifiedResultContext",
        "assess_claim_policy",
        "build_verification_report",
        "compare_verification_results",
          "load_verified_result_context",
          "weakest_claim_level",
        "render_verification_report",
        "export_verified_result",
        "verify_result",
        "write_verification_result",
    },
    "packages": {
        "LocalizationDecision",
        "MetricContract",
        "OPERATOR_GRAPH_BUILDER_ID",
        "OPERATOR_GRAPH_PACKAGE_VERSION",
        "OperatorGraphAdmission",
        "OperatorGraphPlan",
        "PACKAGE_CLAIM_LEVELS",
        "PACKAGE_FILES",
        "PackageClaimContract",
        "PackageSource",
        "QueryCompileResult",
        "RecipeCompileResult",
        "RESEARCH_PACKAGE_VERSION",
        "ResearchPackage",
        "ResearchPackageError",
        "SOURCE_PROVENANCE_MODES",
        "SOURCE_PROVENANCE_VERSION",
        "SOURCE_SNAPSHOT_VERSION",
        "SourceProvenance",
        "compare_research_package_results",
        "compile_package_queries",
        "compile_research_package",
        "default_research_package_template",
        "initialize_research_package",
        "ingest_source_snapshot",
        "load_research_package",
        "render_research_package_report",
        "export_research_package_result",
        "registered_package_builders",
        "validate_package_result",
        "verify_package_source_provenance",
        "verify_source_snapshot",
    },
    "extensions": {
        "EXTENSION_CONTRACT_VERSION",
        "EXTENSION_MANIFEST_VERSION",
        "OPERATOR_CONTRACT_VERSION",
        "OPERATOR_GRAPH_ADMISSION_VERSION",
        "OPERATOR_GRAPH_RECIPE_VERSION",
        "PROJECT_OPERATOR_ABI_VERSION",
        "PROJECT_OPERATOR_BUNDLE_VERSION",
        "PROJECT_OPERATOR_DECLARATION_VERSION",
        "PROJECT_VERIFIER_ABI_VERSION",
        "PROJECT_VERIFIER_BUNDLE_VERSION",
        "STRATEGY_CONTRACT_VERSION",
        "AdmittedOperatorGraph",
        "AdmittedProjectOperatorRegistry",
        "AdmittedProjectVerifier",
        "CompiledExtensionManifest",
        "CompiledOperatorManifest",
        "ControlledExtensionRegistry",
        "DeterminismPolicy",
        "ExtensionDescriptor",
        "ExtensionError",
        "ExtensionKind",
        "ExtensionProjection",
        "InputBinding",
        "OperatorContractError",
        "OperatorDefinition",
        "OperatorGraphRecipe",
        "OperatorImplementationRef",
        "OperatorNodeRecipe",
        "OperatorSpec",
        "ParameterSpec",
        "ParameterType",
        "PortSpec",
        "ProjectArtifactCommit",
        "ProjectArtifactInput",
        "ProjectDirectoryCommit",
        "ProjectOperatorBundleManifest",
        "ProjectVerifierBundleManifest",
        "ProjectOperatorContext",
        "ProjectOperatorDeclaration",
        "ProjectOperatorImplementationToken",
        "ProjectOperatorPermissionProfile",
        "RegisteredExtension",
        "RegisteredOperatorBinding",
        "ResourceProfile",
        "StrategyRole",
        "StrategySelection",
        "StrategySpec",
        "TrustedOperatorRegistry",
        "build_admitted_operator_registry",
        "admit_project_verifier_bundle",
        "compile_extension_manifest",
        "compile_operator_manifest",
        "compile_project_operator_bundle",
        "compile_project_verifier_bundle",
        "load_project_operator_declaration",
        "project_extensions",
        "project_source_hash",
        "verify_project_operator_bundle",
        "verify_project_verifier_bundle",
    },
    "operations": {
        "METADATA_FIELDS",
        "OBSERVABILITY_VERSION",
        "DoctorFinding",
        "DoctorReport",
        "ArtifactGcError",
        "ArtifactGcPlan",
        "GcCandidate",
        "ObservabilityIndexRecord",
        "StructuredLogRecord",
        "apply_artifact_gc",
        "build_structured_log",
        "plan_artifact_gc",
        "purge_artifact_quarantine",
        "rebuild_observability_index",
        "redact_text",
        "run_research_doctor",
        "safe_metadata",
    },
}


def test_mainline_layers_only_import_same_or_lower_layers() -> None:
    for layer, allowed in LAYER_ALLOWED_PREFIXES.items():
        directory = PACKAGE_DIR / layer
        assert directory.is_dir()
        for path in directory.rglob("*.py"):
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            for module in iter_imported_modules(path, tree):
                assert module != INVALID_RELATIVE_IMPORT, (
                    f"{path} 使用了越过 research_pipeline 包根的相对导入"
                )
                if module == "research_pipeline" or module.startswith(
                    "research_pipeline."
                ):
                    assert matches_module_prefix(module, allowed), (
                        f"{layer} 层发生反向依赖: {path} -> {module}"
                    )


def test_package_modules_have_no_ast_import_cycle() -> None:
    package_root = PACKAGE_DIR / "packages"
    module_paths = {}
    for path in package_root.glob("*.py"):
        name = (
            "research_pipeline.packages"
            if path.name == "__init__.py"
            else f"research_pipeline.packages.{path.stem}"
        )
        module_paths[name] = path
    edges = {name: set() for name in module_paths}
    for name, path in module_paths.items():
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        edges[name].update(
            imported
            for imported in iter_imported_modules(path, tree)
            if imported in module_paths and imported != name
        )

    compiler = "research_pipeline.packages.compiler"
    operator_graph = "research_pipeline.packages.operator_graph"
    assert operator_graph not in edges[compiler]
    assert compiler not in edges[operator_graph]

    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(module: str) -> None:
        assert module not in visiting, f"packages 包内出现 AST import 循环: {module}"
        if module in visited:
            return
        visiting.add(module)
        for dependency in edges[module]:
            visit(dependency)
        visiting.remove(module)
        visited.add(module)

    for module in edges:
        visit(module)


def test_directional_gate_rejects_research_dependency_from_platform() -> None:
    tree = ast.parse("from research_pipeline.research import ranking\n")
    modules = iter_imported_modules(PACKAGE_DIR / "platform" / "fixture.py", tree)

    assert "research_pipeline.research" in modules
    assert not matches_module_prefix(
        "research_pipeline.research",
        LAYER_ALLOWED_PREFIXES["platform"],
    )


def test_relative_import_resolver_handles_nested_and_invalid_levels() -> None:
    nested = ast.parse("from .time import TimeContractError\n")
    invalid = ast.parse("from ...v2 import contracts\n")

    assert "research_pipeline.domain.time" in iter_imported_modules(
        PACKAGE_DIR / "domain" / "models.py",
        nested,
    )
    assert INVALID_RELATIVE_IMPORT in iter_imported_modules(
        PACKAGE_DIR / "domain" / "models.py",
        invalid,
    )


def test_mainline_package_roots_have_explicit_version_free_public_api() -> None:
    for layer, expected in EXPECTED_PUBLIC_API.items():
        module = importlib.import_module(f"research_pipeline.{layer}")
        assert set(module.__all__) == expected
        assert all(hasattr(module, name) for name in expected)
        assert all("V2" not in name for name in expected)
