"""新研究主链的不可变金融领域语义。"""

from .models import (
    DomainContractError,
    InstrumentId,
    OrderIntent as LegacyOrderIntent,
    Signal,
    TargetPortfolio,
    TargetWeight,
)
from .trading import (
    INSTRUMENT_KEY_VERSION,
    ORDER_INTENT_VERSION,
    PORTFOLIO_TARGET_VERSION,
    TRADING_RULE_BINDING_VERSION,
    EXECUTION_CAPABILITY_MATRIX,
    InstrumentKey,
    OrderIntent,
    OrderIntentV1,
    PortfolioTarget,
    PortfolioTargetEntry,
    TradingRuleBinding,
    instrument_key_from_legacy,
    portfolio_target_from_legacy,
    require_declared_trading_capability,
)
from .time import (
    CN_MARKET_TIMEZONE,
    FinancialTimeTrace,
    TimeContractError,
    TradingSessionCalendar,
    build_cn_daily_next_open_trace,
    build_completed_bar_trace,
    parse_session,
    require_strict_session_order,
    validate_label_session_horizon,
)
from .instruments import Instrument, InstrumentAlias, resolve_instrument_alias
from .rules import (
    MarketRuleSnapshot,
    RuleBinding,
    resolve_market_rule,
)
from .sessions import SessionSegment, TradingSession
from .session_calendar import (
    SESSION_POLICY_BUNDLE_VERSION,
    SESSION_POLICY_VERSION,
    SessionCalendarError,
    SessionCalendarResolver,
    SessionInstrumentMetadata,
    SessionPolicyBundle,
    SessionPolicyRevision,
    SessionSegmentTemplate,
    load_session_policy_bundle,
)
from .session_close import (
    FUTURES_SESSION_CLOSE_BUNDLE_RESOURCE,
    FUTURES_SESSION_CLOSE_BUNDLE_VERSION,
    FuturesSessionCloseError,
    FuturesSessionClosePolicyBundle,
    load_futures_session_close_bundle,
)
from .session_assignment import (
    SESSION_COMPLETED_BAR_BOUNDARY,
    SESSION_EFFECTIVE_INTERVAL_BOUNDARY,
    SESSION_INSTANT_BOUNDARY,
    SessionAssignmentError,
    SessionAssignmentPolicy,
    assign_completed_bars,
    reconcile_session_aggregates,
)
from .minute_rule_snapshots import (
    CURRENT_MINUTE_RULE_BUNDLE_HASH,
    CURRENT_MINUTE_RULE_COVERAGE_HASH,
    MINUTE_RULE_BUNDLE_VERSION,
    MinuteRuleBinding,
    MinuteRuleResolver,
    MinuteRuleSnapshot,
    MinuteRuleSnapshotBundle,
    MinuteRuleSnapshotError,
    MinuteRuleSource,
    load_minute_rule_snapshot_bundle,
)
from .values import FixedValue, Money, Price, require_integer_quantity
from .corporate_actions import CorporateAction, resolve_corporate_actions
from .market_events import MarketEvent


__all__ = [
    "CN_MARKET_TIMEZONE",
    "CorporateAction",
    "DomainContractError",
    "FinancialTimeTrace",
    "FUTURES_SESSION_CLOSE_BUNDLE_RESOURCE",
    "FUTURES_SESSION_CLOSE_BUNDLE_VERSION",
    "FuturesSessionCloseError",
    "FuturesSessionClosePolicyBundle",
    "FixedValue",
    "Instrument",
    "InstrumentAlias",
    "InstrumentId",
    "InstrumentKey",
    "MarketRuleSnapshot",
    "MarketEvent",
    "CURRENT_MINUTE_RULE_BUNDLE_HASH",
    "CURRENT_MINUTE_RULE_COVERAGE_HASH",
    "MINUTE_RULE_BUNDLE_VERSION",
    "MinuteRuleBinding",
    "MinuteRuleResolver",
    "MinuteRuleSnapshot",
    "MinuteRuleSnapshotBundle",
    "MinuteRuleSnapshotError",
    "MinuteRuleSource",
    "Money",
    "LegacyOrderIntent",
    "OrderIntent",
    "OrderIntentV1",
    "Price",
    "RuleBinding",
    "SESSION_POLICY_BUNDLE_VERSION",
    "SESSION_POLICY_VERSION",
    "SessionCalendarError",
    "SessionCalendarResolver",
    "SESSION_COMPLETED_BAR_BOUNDARY",
    "SESSION_EFFECTIVE_INTERVAL_BOUNDARY",
    "SESSION_INSTANT_BOUNDARY",
    "SessionAssignmentError",
    "SessionAssignmentPolicy",
    "SessionInstrumentMetadata",
    "SessionPolicyBundle",
    "SessionPolicyRevision",
    "SessionSegment",
    "SessionSegmentTemplate",
    "Signal",
    "TargetPortfolio",
    "TargetWeight",
    "PortfolioTarget",
    "PortfolioTargetEntry",
    "TradingRuleBinding",
    "INSTRUMENT_KEY_VERSION",
    "ORDER_INTENT_VERSION",
    "PORTFOLIO_TARGET_VERSION",
    "TRADING_RULE_BINDING_VERSION",
    "EXECUTION_CAPABILITY_MATRIX",
    "TimeContractError",
    "TradingSessionCalendar",
    "TradingSession",
    "build_cn_daily_next_open_trace",
    "build_completed_bar_trace",
    "parse_session",
    "load_session_policy_bundle",
    "load_futures_session_close_bundle",
    "assign_completed_bars",
    "reconcile_session_aggregates",
    "load_minute_rule_snapshot_bundle",
    "require_integer_quantity",
    "require_strict_session_order",
    "resolve_instrument_alias",
    "resolve_market_rule",
    "resolve_corporate_actions",
    "instrument_key_from_legacy",
    "portfolio_target_from_legacy",
    "require_declared_trading_capability",
    "validate_label_session_horizon",
]
