"""股票与 ETF 日频现金仿真的显式目标、行情和历史规则合同。"""
from research_pipeline.extensions import OperatorDefinition, ParameterSpec, ParameterType
from ..operator_definition_factory import _GIB, _definition, _parameter


def build_daily_cash_operator_definitions() -> tuple[OperatorDefinition, ...]:
    return (_definition(
        "finance.simulation.daily-cash", "finance.simulation.daily-cash.v1",
        inputs=(("targets", "research.portfolio-targets.v1"), ("market", "data.daily-market.v1")),
        outputs=(("simulation", "research.daily-simulation.v1"),),
        parameters=(
            ParameterSpec("execution_mode", ParameterType.STRING, required=False,
                          allowed_values=("target", "explicit_orders")),
            ParameterSpec("order_commands", ParameterType.STRING, required=False),
            ParameterSpec("market_rule_profile_id", ParameterType.STRING, required=False,
                          allowed_values=("cn_etf.daily.curated.v1",)),
            _parameter("instrument_codes", ParameterType.STRING_LIST),
            ParameterSpec("market_rules", ParameterType.JSON, required=False),
            ParameterSpec("bond_etf_codes", ParameterType.STRING_LIST_ALLOW_EMPTY, required=False),
            ParameterSpec("equity_etf_codes", ParameterType.STRING_LIST_ALLOW_EMPTY, required=False),
            ParameterSpec("commission_ppm", ParameterType.INTEGER, required=False),
            ParameterSpec("min_commission_units", ParameterType.INTEGER, required=False),
            _parameter("corporate_actions", ParameterType.JSON),
            ParameterSpec("corporate_action_records", ParameterType.JSON, required=False),
            ParameterSpec("account", ParameterType.JSON, required=False),
            ParameterSpec("account_model", ParameterType.STRING, required=False,
                          allowed_values=("cash", "financing_credit")),
            ParameterSpec("credit_account", ParameterType.JSON, required=False),
            ParameterSpec("external_cashflows", ParameterType.STRING, required=False),
            _parameter("initial_cash_cny", ParameterType.NUMBER),
            _parameter("calendar_id", ParameterType.STRING),
            ParameterSpec("non_trading_sessions", ParameterType.JSON, required=False),
            _parameter("policy_available_at", ParameterType.STRING),
        ),
        resource_profile={"memory_bytes": 4 * _GIB, "cpu_slots": 1,
                          "temp_bytes": 8 * _GIB, "wall_seconds": 3600},
        code_fingerprint="daily-cash-historical-rules-explicit-artifacts-v1",
        capability="research.daily-simulation.v1",
        module_name="research_pipeline.runtime.qlib_portfolio_execution",
        symbol_name="execute_daily_cash_artifact",
        implementation_scope="core",
        dependency_modules=(
            "research_pipeline.domain.non_trading_sessions",
            "research_pipeline.domain.order_stream",
            "research_pipeline.domain.external_cashflows",
            "research_pipeline.domain.credit_account",
            "research_pipeline.simulation.credit_account",
            "research_pipeline.simulation.credit_account_execution",
            "research_pipeline.simulation.external_cashflows",
            "research_pipeline.simulation.explicit_orders",
            "research_pipeline.simulation.daily_event",
            "research_pipeline.simulation.daily_financial_context",
            "research_pipeline.simulation.market_rules",
            "research_pipeline.simulation.cash_market",
            "research_pipeline.simulation.cn_etf",
            "research_pipeline.simulation.cn_stock",
            "research_pipeline.simulation.corporate_actions",
            "research_pipeline.simulation.spot_account_execution",
            "research_pipeline.simulation.spot_account",
            "research_pipeline.domain.spot_account",
            "research_pipeline.domain.values",
            "research_pipeline.domain.time",
            "research_pipeline.domain.simulation_result",
            "research_pipeline.simulation.events",
            "research_pipeline.simulation.result_contract",
            "research_pipeline.simulation.bar_tca",
            "research_pipeline.runtime.bar_tca_adapter",
            "research_pipeline.domain.rules",
            "research_pipeline.platform.market_rule_defaults",
        ),
    ),)
