"""新研究主链的金融仿真算法。"""

from importlib import import_module


__all__ = [
    "SIMULATION_INPUT_AVAILABILITY_VERSION",
    "SIMULATION_SEMANTICS_VERSION",
    "SIMULATION_TIMEZONE",
    "SIMULATION_RESULT_CONTRACT_VERSION",
    "SIMULATION_RESULT_SEMANTICS_VERSION",
    "CANONICAL_SIMULATION_TABLES",
    "DAILY_EVENT_SIMULATION_VERSION",
    "FUTURES_DAILY_SIMULATION_VERSION",
    "CapacityMode",
    "ACCOUNT_CONFIG_VERSION",
    "CAPABILITY_MATRIX_VERSION",
    "SIMULATION_REQUEST_VERSION",
    "AccountConfig",
    "CASH_DAILY_BACKEND",
    "CN_FUTURES_DAILY_BACKEND",
    "EXECUTION_BACKENDS",
    "CashExecutionResult",
    "BAR_TCA_ARTIFACT_VERSION",
    "BAR_TCA_ORACLE_INPUT_VERSION",
    "BAR_TCA_POLICY_VERSION",
    "BAR_TCA_RESULT_VERSION",
    "BarTcaFill",
    "BarTcaFormalFill",
    "BarTcaOrder",
    "BarTcaOrderResult",
    "BarTcaPolicy",
    "BarTcaResult",
    "bar_tca_policy_from_parameters",
    "DailyCashSimulationResult",
    "CashReceivable",
    "CashMarketPolicy",
    "ContinuousMapping",
    "ETF_CATEGORIES",
    "EventReplay",
    "ExecutionGroup",
    "ExecutionBackendCapability",
    "FinancialEvent",
    "FuturesLedgerState",
    "FuturesFeePolicy",
    "FuturesLeg",
    "FuturesExecutionRule",
    "FuturesRuleBook",
    "FuturesSimulationResult",
    "FuturesPosition",
    "MarginPolicy",
    "MarginOverride",
    "INTRADAY_EXECUTION_POLICY_VERSION",
    "IntradayExecutionPolicy",
    "MinuteExecutionBar",
    "Order",
    "IntentToOrderPort",
    "OpeningSnapshot",
    "PositionLot",
    "PositionEntitlement",
    "RightsExerciseInstruction",
    "SimulationContractError",
    "SimulationRequest",
    "SimulationResultContract",
    "SimulationResultSemantics",
    "SimulationInputAvailability",
    "SimulationSemanticsV1",
    "SequenceGap",
    "SpotLedgerState",
    "StockPostCloseAudit",
    "TradabilityDecision",
    "TradeReference",
    "evaluate_tradability",
    "compile_corporate_action",
    "compile_cn_etf_corporate_action_rows",
    "compile_cn_stock_corporate_action_rows",
    "corporate_action_snapshot_hash",
    "decompose_roll",
    "deterministic_liquidation_order",
    "etf_policy_from_rule",
    "execute_cash_order",
    "group_etf_policies",
    "margin_call_required",
    "run_minute_event_simulation",
    "run_bar_tca",
    "run_daily_cash_event_simulation",
    "run_futures_daily_simulation",
    "run_futures_portfolio_simulation",
    "project_cash_daily_result",
    "project_futures_daily_result",
    "build_futures_order_intents",
    "build_futures_portfolio_roll_intents",
    "normalize_market_events",
    "reduce_futures",
    "reduce_spot",
    "require_visible_nav",
    "require_declared_execution_capability",
    "require_supported_target",
    "resolve_actual_contract",
    "settle_futures_day",
    "run_market_event_loop",
    "stock_policy_from_rule",
    "stock_policy_from_contract",
    "audit_stock_after_close",
    "build_cn_daily_simulation_semantics",
    "build_simulation_result_contract",
    "canonical_simulation_table",
    "capacity_claim_ceiling",
    "transition_order",
    "verify_simulation_result_artifact",
    "verify_simulation_result_contract",
    "verify_bar_tca_artifact",
    "write_bar_tca_artifact",
    "write_simulation_result_contract",
]


_LAZY_EXPORTS = {
    "TradabilityDecision": ".tradability",
    "TradeReference": ".tradability",
    "evaluate_tradability": ".tradability",
    "FinancialEvent": ".events",
    "CashReceivable": ".ledger",
    "ExecutionGroup": ".ledger",
    "FuturesLedgerState": ".ledger",
    "FuturesPosition": ".ledger",
    "PositionLot": ".ledger",
    "PositionEntitlement": ".ledger",
    "SpotLedgerState": ".ledger",
    "reduce_futures": ".ledger",
    "reduce_spot": ".ledger",
    "Order": ".orders",
    "SimulationContractError": ".orders",
    "transition_order": ".orders",
    "ACCOUNT_CONFIG_VERSION": ".intent_port",
    "CAPABILITY_MATRIX_VERSION": ".intent_port",
    "SIMULATION_REQUEST_VERSION": ".intent_port",
    "AccountConfig": ".intent_port",
    "CASH_DAILY_BACKEND": ".intent_port",
    "CN_FUTURES_DAILY_BACKEND": ".intent_port",
    "EXECUTION_BACKENDS": ".intent_port",
    "ExecutionBackendCapability": ".intent_port",
    "IntentToOrderPort": ".intent_port",
    "SimulationRequest": ".intent_port",
    "require_declared_execution_capability": ".intent_port",
    "require_supported_target": ".intent_port",
    "RightsExerciseInstruction": ".corporate_actions",
    "compile_cn_etf_corporate_action_rows": ".corporate_actions",
    "compile_cn_stock_corporate_action_rows": ".corporate_actions",
    "compile_corporate_action": ".corporate_actions",
    "corporate_action_snapshot_hash": ".corporate_actions",
    "CashExecutionResult": ".cash_market",
    "CashMarketPolicy": ".cash_market",
    "OpeningSnapshot": ".cash_market",
    "execute_cash_order": ".cash_market",
    "BAR_TCA_ARTIFACT_VERSION": ".bar_tca",
    "BAR_TCA_ORACLE_INPUT_VERSION": ".bar_tca",
    "BAR_TCA_POLICY_VERSION": ".bar_tca",
    "BAR_TCA_RESULT_VERSION": ".bar_tca",
    "BarTcaFill": ".bar_tca",
    "BarTcaFormalFill": ".bar_tca",
    "BarTcaOrder": ".bar_tca",
    "BarTcaOrderResult": ".bar_tca",
    "BarTcaPolicy": ".bar_tca",
    "BarTcaResult": ".bar_tca",
    "bar_tca_policy_from_parameters": ".bar_tca",
    "run_bar_tca": ".bar_tca",
    "verify_bar_tca_artifact": ".bar_tca",
    "write_bar_tca_artifact": ".bar_tca",
    "ETF_CATEGORIES": ".cn_etf",
    "etf_policy_from_rule": ".cn_etf",
    "group_etf_policies": ".cn_etf",
    "require_visible_nav": ".cn_etf",
    "StockPostCloseAudit": ".cn_stock",
    "audit_stock_after_close": ".cn_stock",
    "stock_policy_from_contract": ".cn_stock",
    "stock_policy_from_rule": ".cn_stock",
    "MarginPolicy": ".margin",
    "deterministic_liquidation_order": ".margin",
    "INTRADAY_EXECUTION_POLICY_VERSION": ".minute_execution",
    "IntradayExecutionPolicy": ".minute_execution",
    "MinuteExecutionBar": ".minute_execution",
    "run_minute_event_simulation": ".minute_execution",
    "ContinuousMapping": ".cn_futures",
    "FuturesFeePolicy": ".cn_futures",
    "FuturesLeg": ".cn_futures",
    "decompose_roll": ".cn_futures",
    "margin_call_required": ".cn_futures",
    "resolve_actual_contract": ".cn_futures",
    "settle_futures_day": ".cn_futures",
    "EventReplay": ".event_loop",
    "SequenceGap": ".event_loop",
    "normalize_market_events": ".event_loop",
    "run_market_event_loop": ".event_loop",
    "SIMULATION_INPUT_AVAILABILITY_VERSION": ".semantics",
    "SIMULATION_SEMANTICS_VERSION": ".semantics",
    "SIMULATION_TIMEZONE": ".semantics",
    "CapacityMode": ".semantics",
    "SimulationInputAvailability": ".semantics",
    "SimulationSemanticsV1": ".semantics",
    "build_cn_daily_simulation_semantics": ".semantics",
    "capacity_claim_ceiling": ".semantics",
    "CANONICAL_SIMULATION_TABLES": ".result_contract",
    "SIMULATION_RESULT_CONTRACT_VERSION": ".result_contract",
    "SIMULATION_RESULT_SEMANTICS_VERSION": ".result_contract",
    "SimulationResultContract": ".result_contract",
    "SimulationResultSemantics": ".result_contract",
    "build_simulation_result_contract": ".result_contract",
    "canonical_simulation_table": ".result_contract",
    "project_cash_daily_result": ".result_contract",
    "project_futures_daily_result": ".result_contract",
    "verify_simulation_result_artifact": ".result_contract",
    "verify_simulation_result_contract": ".result_contract",
    "write_simulation_result_contract": ".result_contract",
    "DAILY_EVENT_SIMULATION_VERSION": ".daily_event",
    "DailyCashSimulationResult": ".daily_event",
    "run_daily_cash_event_simulation": ".daily_event",
    "FUTURES_DAILY_SIMULATION_VERSION": ".futures_daily",
    "FuturesExecutionRule": ".futures_daily",
    "FuturesRuleBook": ".futures_daily",
    "FuturesSimulationResult": ".futures_daily",
    "MarginOverride": ".futures_daily",
    "build_futures_order_intents": ".futures_daily",
    "run_futures_daily_simulation": ".futures_daily",
    "build_futures_portfolio_roll_intents": ".futures_portfolio",
    "run_futures_portfolio_simulation": ".futures_portfolio",
}


def __getattr__(name: str):
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value
