"""新研究主链的只读列式数据平面。"""

from importlib import import_module

from .errors import DataPlaneError, DataPlaneRequestExecutionError, ProviderExecutionError, QualityGateError, QueryAttestationStaleError, QueryCatalogUnapprovedError, QueryIRInvalidError, QueryUnboundedError, SnapshotIntegrityError, SourceChangedError
from .path_policy import PathRolePolicy
from .query_ir import (
    DATE_RANGE_V1_VERSION,
    INSTANT_RANGE_V2_VERSION,
    QUERY_IR_V2_VERSION,
    DateRangeV1,
    FilterOperator,
    FilterPredicate,
    InstantRangeV2,
    QueryBudget,
    QueryIR,
    QueryPurpose,
    SortKey,
    UniverseSelection,
    parse_aware_datetime,
    resolve_as_of_cutoff,
)

__all__ = [
    "ADMITTED_PLAN_VERSION", "DATASET_ARTIFACT_REF_VERSION", "AdmittedQueryPlan", "ArtifactResolver",
    "ColumnarStream", "DataPlaneExecutionBudget", "DuckDBColumnarProvider", "ExecutionEstimate",
    "DataPlaneError", "DataPlaneRequestExecutionError", "ProviderExecutionError", "QualityGateError",
    "FUTURES_D0_PROFILE_VERSION", "FUTURES_D0_RECEIPT_VERSION", "FUTURES_D0_REPORT_VERSION",
    "FuturesD0Profile", "FuturesD0Report",
    "FUTURES_EXECUTION_EVIDENCE_VERSION", "FUTURES_EXECUTION_RECEIPT_VERSION",
    "ExecutionPricePolicy",
    "DatasetArtifactRef", "DatasetFilter", "FilterOperator", "FilterPredicate", "LogicalSnapshot",
    "PARTITIONED_DATASET_CONTRACT", "PARTITIONED_DATASET_REF_CONTRACT",
    "DatasetPartitionRef", "PartitionedDatasetRef", "PartitionedDatasetResolver",
    "VerifiedDatasetPartition", "VerifiedPartitionedDataset", "inspect_parquet_partition",
    "ParquetColumnarProvider", "PathRolePolicy", "ProviderExecutionPlan",
    "PhysicalSnapshotPolicy", "QualityGateSession", "QueryBudget", "QueryEstimate",
    "QueryIR", "QueryPurpose", "ReadOnlyColumnarProvider",
    "QueryAttestationStaleError", "QueryCatalogUnapprovedError", "QueryIRInvalidError", "QueryUnboundedError",
    "DATE_RANGE_V1_VERSION", "DateRangeV1", "INSTANT_RANGE_V2_VERSION",
    "InstantRangeV2", "QUERY_IR_V2_VERSION", "SortKey", "SourceRevision",
    "EffectiveIntervalSelector", "RevisionSelector", "SelectionClock",
      "SessionCloseFact", "SessionCloseInstrumentBinding", "SessionCloseSelection",
    "TemporalSelectionPlan", "VisibilityFilter",
    "AVG_POLICY", "SUPPORTED_MINUTE_INTERVALS",
    "parse_aware_datetime", "resolve_as_of_cutoff",
    "MINUTE_ADJUSTMENT_MANIFEST_VERSION",
    "MinuteAdjustmentManifest", "MinuteAdjustmentStream",
    "MinuteBucketSpec", "MinuteResampleBudget", "MinuteResampleManifest",
    "MinutePartitionQualityReceipt", "MinuteResamplePlan", "MinuteResampleStream", "MinuteScanBudget",
    "MinuteScanPlan", "MinuteSourcePartition",
    "MINUTE_ADJUSTMENT_AUDIT_VERSION", "MINUTE_QUALITY_PROFILE_VERSION",
    "MINUTE_QUALITY_REPORT_VERSION", "AdjustmentRelationSample",
    "MinuteAdjustmentAudit", "MinuteQualityIssue", "MinuteQualityProfile",
    "MinuteQualityReport",
    "RunScopedArtifactVerification", "ScanBenchmark", "SnapshotIntegrityError", "SourceChangedError", "VerifiedDataset",
    "UniverseSelection", "admit_query", "benchmark_verified_scan", "build_dataset_artifact_ref", "build_logical_snapshot",
    "gate_policy_hash",
    "preflight_estimate", "probe_duckdb_source", "probe_parquet_source", "require_scan_benchmark",
    "activate_artifact_verification", "publish_parquet_snapshot", "require_source_unchanged",
    "validate_publish_manifest", "validate_table", "verify_parquet_snapshot",
    "VerifiedMinutePartitionStream", "build_minute_partitioned_dataset", "build_minute_resample_plan", "build_minute_scan_plan", "execute_minute_resample", "minute_resample_schema",
    "build_adjustment_factor_snapshot", "execute_minute_adjustment",
    "rebase_pre_window",
    "resolve_pre_anchor_factor",
    "round_ex_reference_price",
    "require_minute_price_mode",
    "audit_adjustment_gate", "audit_minute_quality",
    "audit_futures_daily_data",
    "audit_futures_execution_evidence",
    "default_execution_price_policies",
    "require_minute_quality_pass",
    "require_futures_d0_receipt",
]


_LAZY_EXPORTS = {
    "ADMITTED_PLAN_VERSION": ".admission",
    "AdmittedQueryPlan": ".admission",
    "admit_query": ".admission",
    "ScanBenchmark": ".benchmark",
    "benchmark_verified_scan": ".benchmark",
    "require_scan_benchmark": ".benchmark",
    "DATASET_ARTIFACT_REF_VERSION": ".dataset_artifacts",
    "ArtifactResolver": ".dataset_artifacts",
    "DatasetArtifactRef": ".dataset_artifacts",
    "DatasetFilter": ".dataset_artifacts",
    "VerifiedDataset": ".dataset_artifacts",
    "build_dataset_artifact_ref": ".dataset_artifacts",
    "RunScopedArtifactVerification": ".verification_lifecycle",
    "activate_artifact_verification": ".verification_lifecycle",
    "FUTURES_D0_PROFILE_VERSION": ".futures_daily_audit",
    "FUTURES_D0_RECEIPT_VERSION": ".futures_daily_audit",
    "FUTURES_D0_REPORT_VERSION": ".futures_daily_audit",
    "FuturesD0Profile": ".futures_daily_audit",
    "FuturesD0Report": ".futures_daily_audit",
    "audit_futures_daily_data": ".futures_daily_audit",
    "require_futures_d0_receipt": ".futures_daily_audit",
    "FUTURES_EXECUTION_EVIDENCE_VERSION": ".futures_execution_policy",
    "FUTURES_EXECUTION_RECEIPT_VERSION": ".futures_execution_policy",
    "ExecutionPricePolicy": ".futures_execution_policy",
    "audit_futures_execution_evidence": ".futures_execution_policy",
    "default_execution_price_policies": ".futures_execution_policy",
    "QualityGateSession": ".gates",
    "QueryEstimate": ".gates",
    "gate_policy_hash": ".gates",
    "preflight_estimate": ".gates",
    "validate_publish_manifest": ".gates",
    "validate_table": ".gates",
    "DataPlaneExecutionBudget": ".execution_budget",
    "ExecutionEstimate": ".execution_estimate",
    "ProviderExecutionPlan": ".execution_budget",
    "AVG_POLICY": ".minute_resampling",
    "SUPPORTED_MINUTE_INTERVALS": ".minute_resampling",
    "MinuteBucketSpec": ".minute_resampling",
    "MinuteResampleBudget": ".minute_resampling",
    "MinuteResampleManifest": ".minute_resampling",
    "MinuteResamplePlan": ".minute_resampling",
    "MinuteResampleStream": ".minute_resampling",
    "build_minute_resample_plan": ".minute_resampling",
    "execute_minute_resample": ".minute_resampling",
    "minute_resample_schema": ".minute_resampling",
    "MinuteScanBudget": ".minute_scan",
    "MinuteScanPlan": ".minute_scan",
    "MinuteSourcePartition": ".minute_scan",
    "build_minute_partitioned_dataset": ".minute_scan",
    "build_minute_scan_plan": ".minute_scan",
    "MINUTE_ADJUSTMENT_AUDIT_VERSION": ".minute_quality",
    "MINUTE_QUALITY_PROFILE_VERSION": ".minute_quality",
    "MINUTE_QUALITY_REPORT_VERSION": ".minute_quality",
    "AdjustmentRelationSample": ".minute_quality",
    "MinuteAdjustmentAudit": ".minute_quality",
    "MinuteQualityIssue": ".minute_quality",
    "MinuteQualityProfile": ".minute_quality",
    "MinuteQualityReport": ".minute_quality",
    "audit_adjustment_gate": ".minute_quality",
    "audit_minute_quality": ".minute_quality",
    "require_minute_quality_pass": ".minute_quality",
    "PARTITIONED_DATASET_CONTRACT": ".partitioned_artifacts",
    "PARTITIONED_DATASET_REF_CONTRACT": ".partitioned_artifacts",
    "DatasetPartitionRef": ".partitioned_artifacts",
    "PartitionedDatasetRef": ".partitioned_artifacts",
    "PartitionedDatasetResolver": ".partitioned_artifacts",
    "VerifiedDatasetPartition": ".partitioned_artifacts",
    "VerifiedPartitionedDataset": ".partitioned_artifacts",
    "inspect_parquet_partition": ".partitioned_artifacts",
    "MINUTE_ADJUSTMENT_MANIFEST_VERSION": ".minute_adjustment",
    "MinuteAdjustmentManifest": ".minute_adjustment",
    "MinuteAdjustmentStream": ".minute_adjustment",
    "build_adjustment_factor_snapshot": ".minute_adjustment",
    "execute_minute_adjustment": ".minute_adjustment",
    "rebase_pre_window": ".minute_adjustment",
    "resolve_pre_anchor_factor": ".minute_adjustment",
    "require_minute_price_mode": ".minute_adjustment",
    "round_ex_reference_price": ".minute_adjustment",
    "MinutePartitionQualityReceipt": ".minute_partition_streaming",
    "VerifiedMinutePartitionStream": ".minute_partition_streaming",
    "DuckDBColumnarProvider": ".providers",
    "ParquetColumnarProvider": ".providers",
    "ReadOnlyColumnarProvider": ".providers",
    "SourceRevision": ".revision",
    "probe_duckdb_source": ".revision",
    "probe_parquet_source": ".revision",
    "require_source_unchanged": ".revision",
    "LogicalSnapshot": ".snapshot_identity",
    "build_logical_snapshot": ".snapshot_identity",
    "PhysicalSnapshotPolicy": ".snapshots",
    "publish_parquet_snapshot": ".snapshots",
    "verify_parquet_snapshot": ".snapshots",
    "ColumnarStream": ".stream",
    "EffectiveIntervalSelector": ".temporal",
    "RevisionSelector": ".temporal",
    "SelectionClock": ".temporal",
    "SessionCloseFact": ".temporal",
      "SessionCloseInstrumentBinding": ".temporal",
    "SessionCloseSelection": ".temporal",
    "TemporalSelectionPlan": ".temporal",
    "VisibilityFilter": ".temporal",
}


def __getattr__(name: str):
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value
